import type { ExpressionItem, VocabularyItem } from "@/types";

/**
 * Curated learning content (vocabulary + expressions). This is static app
 * content, not user data — user interactions with these items (saved /
 * learned) are persisted per-user in Supabase (see vocabulary_progress).
 */

export const VOCABULARY: VocabularyItem[] = [
  { id: "v1", italian: "Ciao", japanese: "こんにちは", reading: "konnichiwa", english: "Hello", category: "Greetings" },
  { id: "v2", italian: "Grazie", japanese: "ありがとう", reading: "arigatou", english: "Thank you", category: "Greetings" },
  { id: "v3", italian: "Amicizia", japanese: "友情", reading: "yuujou", english: "Friendship", category: "Relationships" },
  { id: "v4", italian: "Viaggio", japanese: "旅行", reading: "ryokou", english: "Trip / Journey", category: "Travel" },
  { id: "v5", italian: "Cultura", japanese: "文化", reading: "bunka", english: "Culture", category: "Society" },
  { id: "v6", italian: "Cibo", japanese: "食べ物", reading: "tabemono", english: "Food", category: "Daily life" },
  { id: "v7", italian: "Famiglia", japanese: "家族", reading: "kazoku", english: "Family", category: "Relationships" },
  { id: "v8", italian: "Scuola", japanese: "学校", reading: "gakkou", english: "School", category: "Daily life" },
  { id: "v9", italian: "Buongiorno", japanese: "おはよう", reading: "ohayou", english: "Good morning", category: "Greetings" },
  { id: "v10", italian: "Buonanotte", japanese: "おやすみ", reading: "oyasumi", english: "Good night", category: "Greetings" },
  { id: "v11", italian: "Scusa", japanese: "すみません", reading: "sumimasen", english: "Excuse me / Sorry", category: "Greetings" },
  { id: "v12", italian: "Prego", japanese: "どういたしまして", reading: "dou itashimashite", english: "You're welcome", category: "Greetings" },
  { id: "v13", italian: "Acqua", japanese: "水", reading: "mizu", english: "Water", category: "Daily life" },
  { id: "v14", italian: "Caffè", japanese: "コーヒー", reading: "koohii", english: "Coffee", category: "Food" },
  { id: "v15", italian: "Riso", japanese: "米", reading: "kome", english: "Rice", category: "Food" },
  { id: "v16", italian: "Pesce", japanese: "魚", reading: "sakana", english: "Fish", category: "Food" },
  { id: "v17", italian: "Frutta", japanese: "果物", reading: "kudamono", english: "Fruit", category: "Food" },
  { id: "v18", italian: "Treno", japanese: "電車", reading: "densha", english: "Train", category: "Travel" },
  { id: "v19", italian: "Aeroporto", japanese: "空港", reading: "kuukou", english: "Airport", category: "Travel" },
  { id: "v20", italian: "Montagna", japanese: "山", reading: "yama", english: "Mountain", category: "Travel" },
  { id: "v21", italian: "Mare", japanese: "海", reading: "umi", english: "Sea", category: "Travel" },
  { id: "v22", italian: "Città", japanese: "都市", reading: "toshi", english: "City", category: "Travel" },
  { id: "v23", italian: "Lavoro", japanese: "仕事", reading: "shigoto", english: "Work / Job", category: "Daily life" },
  { id: "v24", italian: "Tempo", japanese: "天気", reading: "tenki", english: "Weather", category: "Daily life" },
  { id: "v25", italian: "Musica", japanese: "音楽", reading: "ongaku", english: "Music", category: "Society" },
  { id: "v26", italian: "Libro", japanese: "本", reading: "hon", english: "Book", category: "Society" },
  { id: "v27", italian: "Felice", japanese: "幸せ", reading: "shiawase", english: "Happy", category: "Emotions" },
  { id: "v28", italian: "Triste", japanese: "悲しい", reading: "kanashii", english: "Sad", category: "Emotions" },
  { id: "v29", italian: "Stanco", japanese: "疲れた", reading: "tsukareta", english: "Tired", category: "Emotions" },
  { id: "v30", italian: "Emozionato", japanese: "興奮した", reading: "koufun shita", english: "Excited", category: "Emotions" },
  { id: "v31", italian: "Uno", japanese: "一", reading: "ichi", english: "One", category: "Numbers" },
  { id: "v32", italian: "Due", japanese: "二", reading: "ni", english: "Two", category: "Numbers" },
  { id: "v33", italian: "Tre", japanese: "三", reading: "san", english: "Three", category: "Numbers" },
  { id: "v34", italian: "Dieci", japanese: "十", reading: "juu", english: "Ten", category: "Numbers" },
  { id: "v35", italian: "Oggi", japanese: "今日", reading: "kyou", english: "Today", category: "Time" },
  { id: "v36", italian: "Domani", japanese: "明日", reading: "ashita", english: "Tomorrow", category: "Time" },
  { id: "v37", italian: "Ieri", japanese: "昨日", reading: "kinou", english: "Yesterday", category: "Time" },
];

export const EXPRESSIONS: ExpressionItem[] = [
  {
    id: "e1",
    italian: "Piacere di conoscerti",
    japanese: "はじめまして",
    reading: "hajimemashite",
    english: "Nice to meet you",
    context: "First meeting",
  },
  {
    id: "e2",
    italian: "Come stai?",
    japanese: "元気ですか？",
    reading: "genki desu ka",
    english: "How are you?",
    context: "Everyday conversation",
  },
  {
    id: "e3",
    italian: "A presto!",
    japanese: "またね",
    reading: "mata ne",
    english: "See you soon",
    context: "Saying goodbye",
  },
  {
    id: "e4",
    italian: "Buon appetito",
    japanese: "いただきます",
    reading: "itadakimasu",
    english: "Enjoy your meal",
    context: "Before eating",
  },
  {
    id: "e5",
    italian: "Non capisco",
    japanese: "分かりません",
    reading: "wakarimasen",
    english: "I don't understand",
    context: "Everyday conversation",
  },
  {
    id: "e6",
    italian: "Puoi ripetere, per favore?",
    japanese: "もう一度お願いします",
    reading: "mou ichido onegaishimasu",
    english: "Could you repeat that, please?",
    context: "Everyday conversation",
  },
  {
    id: "e7",
    italian: "Quanto costa?",
    japanese: "いくらですか？",
    reading: "ikura desu ka",
    english: "How much is it?",
    context: "Shopping",
  },
  {
    id: "e8",
    italian: "Dov'è il bagno?",
    japanese: "トイレはどこですか？",
    reading: "toire wa doko desu ka",
    english: "Where is the bathroom?",
    context: "Travel",
  },
  {
    id: "e9",
    italian: "Mi chiamo...",
    japanese: "私の名前は...です",
    reading: "watashi no namae wa ... desu",
    english: "My name is...",
    context: "First meeting",
  },
  {
    id: "e10",
    italian: "Congratulazioni!",
    japanese: "おめでとう",
    reading: "omedetou",
    english: "Congratulations!",
    context: "Celebrations",
  },
  {
    id: "e11",
    italian: "In bocca al lupo",
    japanese: "頑張って",
    reading: "ganbatte",
    english: "Good luck",
    context: "Encouragement",
  },
  {
    id: "e12",
    italian: "Sono d'accordo",
    japanese: "賛成です",
    reading: "sansei desu",
    english: "I agree",
    context: "Everyday conversation",
  },
  {
    id: "e13",
    italian: "Non lo so",
    japanese: "分かりません",
    reading: "wakarimasen",
    english: "I don't know",
    context: "Everyday conversation",
  },
  {
    id: "e14",
    italian: "Che bello!",
    japanese: "すごいですね",
    reading: "sugoi desu ne",
    english: "That's amazing!",
    context: "Reactions",
  },
];
